// -----------------------------------------------------------------------

function windowWidthChanger_changeWidth(){
    var style = document.getElementsByClassName('contents')[0].style
    if(style.maxWidth == "100%"){
        style.maxWidth = "";
    } else {
        style.maxWidth = "100%";
    }
}

// -----------------------------------------------------------------------

function add_WindowWidthChanger(){
 var widthChanger = document.createElement("button");
 //widthChanger.classList.add("button");
 widthChanger.innerHTML = "toogle content width";
 widthChanger.onclick = windowWidthChanger_changeWidth;

 // add to site
 document.body.insertBefore(widthChanger,document.body.firstChild); 
}

// -----------------------------------------------------------------------

function add_homeLink(){
    var homeLink = document.createElement("span");
    homeLink.classList.add("homeLink");
    homeLink.innerHTML = '<a href="../index.html">↑ home</a>';

     // add to site
    document.body.insertBefore(homeLink,document.body.firstChild); 
}

// -----------------------------------------------------------------------

function createTOC(){

    var tocRoot = document.createElement("div");
    tocRoot.innerHTML = `<div>
                    <div class="tocDiv">  
                    <div class="tocTitle">Contents</div>
                    <div id="toc">
                        <!-- generated by javascript -->
                    </div>
                    </div>`;
                    
    // add to site
    document.body.insertBefore(tocRoot,document.body.firstChild); 

    var documentRef = documentRef || document;
    var toc = documentRef.getElementById("toc");
    //  Use headings inside <article> only:
    //  var headings = [].slice.call(documentRef.body.querySelectorAll('article h1, article h2, article h3, article h4, article h5, article h6'));
    var headings = [].slice.call(documentRef.body.querySelectorAll('h1, h2, h3, h4'));
    headings.forEach(function (heading, index) {
        var ref = "toc" + index;
        if ( heading.hasAttribute( "id" ) ) 
            ref = heading.getAttribute( "id" );
        else
            heading.setAttribute( "id", ref );

        var link = documentRef.createElement( "a" );
        link.setAttribute( "href", "#"+ ref );
        link.textContent = heading.textContent;

        var div = documentRef.createElement( "div" );
        div.setAttribute( "class", heading.tagName.toLowerCase() );
        div.appendChild( link );
        toc.appendChild( div );
    });
}
// -----------------------------------------------------------------------

window.onload = function () {
    createTOC();
    add_WindowWidthChanger();
    add_homeLink();
}

// -----------------------------------------------------------------------

try {
    module.exports = htmlTableOfContents;
} catch (e) {
    // module.exports is not defined
};

// -----------------------------------------------------------------------